- name: frontend configure
  hosts: frontend
  become: yes
  vars:

  tasks:
  - name: Install Nginx
    ansible.builtin.dnf:
      name: nginx
      state: latest

  - name: Enable nginx and Start nginx
    ansible.builtin.service:
      name: nginx
      enabled: yes
      state: started

  - name: Recursively remove directory
    ansible.builtin.file:
      path: /usr/share/nginx/html/
      state: absent
    
  - name: Create a directory if it does not exist
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: directory

  - name: Download frontend code
    ansible.builtin.get_url:
      url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
      dest: /tmp/frontend.zip
    
  - name: Unzip the frontend content.
    ansible.builtin.unarchive:
      src: /tmp/frontend.zip
      dest: /usr/share/nginx/html
      remote_src: yes

  - name: Create Nginx Reverse Proxy Configuration
    ansible.builtin.copy:
      src: expense.conf
      dest: /etc/nginx/default.d/expense.conf

  - name: Restart service httpd, in all cases
    ansible.builtin.service:
      name: nginx
      state: restarted
  
    
  